package main

import (
	"log"
	"net/http"

	"auth-service/internal/auth"
	"auth-service/internal/config"
	"auth-service/internal/database"
	"auth-service/internal/handlers"
	"auth-service/internal/middleware"
	"auth-service/internal/repositories"
	"auth-service/internal/services"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "auth-service/docs" // docs is generated by Swag CLI
)

// @title Auth Service API
// @version 1.0
// @description This is a sample server for a auth service.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8081
// @BasePath /api/v1
func main() {
	cfg, err := config.LoadConfig("config/config.yaml")
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	db, err := database.NewDatabase(cfg)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	if err := db.AutoMigrate(); err != nil {
		log.Fatalf("Failed to migrate database: %v", err)
	}

	userRepo := repositories.NewUserRepository(db.GetDB())
	jwtService := auth.NewJWTService(cfg.JWT.Secret, cfg.JWT.ExpirationTime)

	authService := services.NewAuthService(userRepo, jwtService)
	authHandler := handlers.NewAuthHandler(authService)

	gin.SetMode(gin.ReleaseMode)
	router := gin.New()
	router.Use(gin.Logger())
	router.Use(middleware.PrometheusMiddleware())

	// Swagger endpoint
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	api := router.Group("/api/v1")
	{
		auth := api.Group("/auth")
		{
			auth.POST("/register", authHandler.Register)
			auth.POST("/login", authHandler.Login)
			auth.GET("/validate", authHandler.ValidateToken)
			//auth.GET("/users/:id", authHandler.GetUser)
		}
	}

	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"status":  "healthy",
			"service": "auth-service",
		})
	})

	// Prometheus metrics endpoint
	router.GET("/metrics", gin.WrapH(promhttp.Handler()))

	// var wg sync.WaitGroup
	// wg.Add(1)
	// go func() {
	// 	defer wg.Done()
	// 	metricsRouter := gin.New()
	// 	metricsRouter.GET("/metrics", gin.WrapH(promhttp.Handler()))

	// 	log.Printf("Order service metrics starting on %s", cfg.GetPrometheusAddr())
	// 	if err := metricsRouter.Run(cfg.GetPrometheusAddr()); err != nil {
	// 		log.Printf("Failed to start metrics server: %v", err)
	// 	}
	// }()

	log.Printf("Auth service starting on %s", cfg.GetServerAddr())

	// Start main server
	if err := router.Run(cfg.GetServerAddr()); err != nil {
		log.Fatalf("Failed to start auth service: %v", err)
	}
}
