apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: app-system-operator
  name: app-system-operator-controller-manager
  namespace: {{ default "app-engine" .Release.Namespace }}
